server:
  port: 4000
  
spring: 
  application: 
    name: atguigu-consumer          # consumer微服务的名称
    
eureka: 
  client: 
    serviceUrl:                     # 通过如下地址找到Eureka注册中心
      defaultZone: http://localhost:5000/eureka/