server:
  port: 9000
  servlet:
    context-path: /dog
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
zuul:
  ignored-services: '*'
  prefix: /cat
  routes:
    employee:
      service-id: atguigu-feign-consumer
      path: /zuul-emp/**